# Numpy 라이브러리
- 빅데이터의 수학적, 과학적 계산을 위해 만들어진 라이브러리
- 반복문 없이 전체 데이터의 연산이 가능한 표준 수학 함수들을 제공
- ※배열: 같은 자료형의 값들이 연속적인 형태로 구성된 자료 구조로 대량의 데이터를 그룹으로 관리하고 계산하기 위해 사용!

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
# Numpy 라이브러리를 불러와서 np로 지칭하겠다!
import numpy as np

In [9]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [10]:
type(list1)  # list1의 type은 list

list

In [11]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)  # 넘파이.다차원

numpy.ndarray

## 1차원 배열


In [13]:
arr = np.array([1,2,3]) 
arr

array([1, 2, 3])

In [14]:
arr = np.array([1,2,3.5])  # 하나의 데이터 형태로 전부 바뀜
arr

array([1. , 2. , 3.5])

In [15]:
arr = np.array([1,2,"야호!"])   # 하나의 데이터 형태로 전부 바뀜
arr

array(['1', '2', '야호!'], dtype='<U11')

## 2차원 배열

In [16]:
arr2 = np.array([[1,2,3],[4,5,6]])      #가로 X행 세로 Y열 2차원배열
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# 배열의 형태 확인(X행,Y열)
arr2.shape
#2행3열

(2, 3)

In [18]:
# 배열의 요소 전체 개수
arr2.size  # 1 ~ 6 까지 6개

6

In [19]:
# 배열의 데이터 타입(자료형 확인)
arr2.dtype 
# 32는 bit를 뜻함(기계가 표현할 수 있는 범위) → 2^32
#int8 => 1비트당 2개의 숫자를 표현할 수 있음 2^8 = 256개 표현 가능 (-128 ~ 127)
#int32 => -2,147,483,648 ~ 2,147,483,647

dtype('int32')

In [20]:
# 배열의 차원 확인
arr2.ndim

2

In [21]:
# 예제
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

- arr3배열의 형태, 차원, 전체요소 개수를 출력해보세요~!

In [22]:
print("배열의 형태 :", arr3.shape) # 2행2열의 배열이 2개(개수, 행수, 열수)
print("배열의 차원 :", arr3.ndim)
print("배열의 전체요소개수 :", arr3.size)

배열의 형태 : (2, 2, 2)
배열의 차원 : 3
배열의 전체요소개수 : 8


In [23]:
# 0으로 배열 생성
arr_zeros = np.zeros((2,3,4))   # 2개 3행 4열
arr_zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
# 1로 배열 생성
arr_ones = np.ones((2,4,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
# 득정값으로 배열 생성하기
arr_full = np.full((5,5),2) # 5행 5열 2로 생성하기
arr_full

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])